name: Latest Release Monitor
description: Keep track of the latest releases of insiders and stable and trigger webhook events when they change
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  storageKey:
    description: Azure blob storage connection string
    required: true
runs:
  using: 'node16'
  main: 'index.js'
