name: Checks for Valid Issues and PRs
description: Checks for valid issues and PRs in the destination repo
inputs:
  token:
    description: GitHub token with issue read/write permissions to both repos
  app_id:
    description: GitHub App ID
    required: false
  app_installation_id:
    description: GitHub App Installation ID
    required: false
  app_private_key:
    description: GitHub App Private Key
    required: false
  owner:
    description: Repository owner
    required: false
  repo:
    description: Repository name
    required: false
  issue_number:
    description: Issue number
    required: false
  event:
    description: Event name for a triggered action. Otherwise, this is obtained from the github context.
    required: false
  action:
    description: Action name for a triggered action. Otherwise, this is obtained from the github context.
    required: false

runs:
  using: 'node20'
  main: 'index.js'
