name: 'Test Plan Item Validator'
description: Tag issues that don't contain important info
inputs:
  app_id:
    description: GitHub App ID
    required: true
  app_installation_id:
    description: GitHub App Installation ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true
  owner:
    description: Repository owner
    required: true
  repo:
    description: Repository name
    required: true
  issue_number:
    description: Issue number
    required: true
  label:
    description: The label that signifies an item is a testplan item and should be checked
    required: true
  refLabel:
    description: The label to apply to referenced issues
    default: 'on-testplan'
    required: true
  invalidLabel:
    description: The label to add when a test plan item is invalid
    required: true
  comment:
    description: Comment to post to invalid test plan items
    required: true
runs:
  using: 'node20'
  main: 'index.js'
