name: 'Review Reminder'
description: 'Notify in chat about build results.'
author: 'Logan Ramos'
inputs:
  app_id:
    description: GitHub App ID
    required: true
  app_installation_id:
    description: GitHub App Installation ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true
  slack_token:
    description: Slack token.
    required: true
runs:
  using: 'node20'
  main: 'index.js'
