name: Needs More Info Closer
description: Close issues that are marked a needs more info label and were last interacted with by a contributor or bot
inputs:
  app_id:
    description: GitHub App ID
    required: true
  app_installation_id:
    description: GitHub App Installation ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true
  owner:
    description: Repository owner
    required: true
  repo:
    description: Repository name
    required: true
  label:
    description: Label signifying an issue that needs more info
    required: true
  closeDays:
    description: Days to wait before closing the issue
    required: true
  closeComment:
    description: Comment to add upon closing the issue
  pingDays:
    description: Days to wait before pinging the assignee
    required: true
  additionalTeam:
    description: Pipe-separated list of users to treat as team for purposes of closing `needs more info` issues
  pingComment:
    description: Comment to add when pinging assignee. ${assignee} and ${author} are replaced.
runs:
  using: 'node20'
  main: 'index.js'
