name: Author Verified
description: Allow issue authors to verify their own issues by pinging them when the fix goes into insiders
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
  app_id:
    description: GitHub App ID
    required: false
  app_installation_id:
    description: GitHub App Installation ID
    required: false
  app_private_key:
    description: GitHub App Private Key
    required: false
  owner:
    description: Repository owner
    required: false
  repo:
    description: Repository name
    required: false
  issue_number:
    description: Issue number
    required: false
  event:
    description: Event name for a triggered action. Otherwise, this is obtained from the github context.
    required: false
  action:
    description: Action name for a triggered action. Otherwise, this is obtained from the github context.
    required: false
  requestVerificationComment:
    description: Comment to add whenn asking authors to verify the issue. ${commit} and ${author} will be substituted
    required: true
  releasedLabel:
    description: Label of issues which are released and thus able to be verified
    required: true
  verifiedLabel:
    description: Label of issues that are laready verified and shouldn't be further interacted with
    required: true
  authorVerificationRequestedLabel:
    description: Label added by issue fixer to signal that the author can verify the issue
    required: true
runs:
  using: 'node20'
  main: 'index.js'
