name: "Classifier: Monitor"
description: Alerts when assignees added by the bot are unassigned
inputs:
  app_id:
    description: GitHub App ID
    required: true
  app_installation_id:
    description: GitHub App Installation ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true
  owner:
    description: Repository owner
    required: true
  repo:
    description: Repository name
    required: true
  issue_number:
    description: Issue number
    required: true
  event:
    description: Event name for a triggered action. Otherwise, this is obtained from the github context.
    required: true
  action:
    description: Action name for a triggered action. Otherwise, this is obtained from the github context.
    required: true
  payload:
    description: Payload object for the github action
    required: true
  botName:
    description: The login of the bot
    required: true
runs:
  using: 'node20'
  main: 'index.js'
