name: Latest Release Monitor
description: Keep track of the latest releases of insiders and stable and trigger webhook events when they change
inputs:
  token:
    description: GitHub Token
  app_id:
    description: GitHub App ID
  app_installation_id:
    description: GitHub App Installation ID
  app_private_key:
    description: GitHub App Private Key
  owner:
    description: Repository owner
  repo:
    description: Repository name
runs:
  using: 'node20'
  main: 'index.js'
