name: Latest Release Monitor
description: Keep track of the latest releases of insiders and stable and trigger webhook events when they change
inputs:
  app_id:
    description: GitHub App ID
    required: true
  app_installation_id:
    description: GitHub App Installation ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true
  owner:
    description: Repository owner
    required: true
  repo:
    description: Repository name
    required: true
runs:
  using: 'node20'
  main: 'index.js'
