name: Locker
description: Lock closed issues and PRs after some time has passed
inputs:
  app_id:
    description: GitHub App ID
    required: true
  app_installation_id:
    description: GitHub App Installation ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true
  owner:
    description: Repository owner
    required: true
  repo:
    description: Repository name
    required: true
  daysSinceClose:
    description: Days to wait since closing before locking the item
    required: true
  daysSinceUpdate:
    description: days to wait since the last interaction before locking the item
    required: true
  ignoredLabel:
    description: items with this label will not be automatically locked
  ignoreLabelUntil:
    description: items with this label will not be automatically locked, until they also have the until label
  ignoredMilestones:
    description: items in any of these milestones will not be automatically locked
  labelUntil:
    description: items with this will not automatically locked, even if they have the ignoreLabelUntil label
  typeIs:
    description: either 'issue' or 'pr' to limit the query to only those types
runs:
  using: 'node20'
  main: 'index.js'
