name: 'Code Review Chat'
description: 'Notify in chat about build results.'
author: 'Jackson Kearl / Logan Ramos'
inputs:
  token:
    description: GitHub token.
    default: ${{ github.token }}
    required: true
  slack_token:
    description: Slack token.
    required: true
  slack_user_token:
    description: 'Elevated user token for actions requiring admin'
    required: false
  notification_channel_id:
    description: 'Which channel to send notifications to. Defaults to none.'
    required: true
  slack_bot_name:
    description: 'Required when doing using in queue mode (deletions enabled on close)'
    required: true
  tenantId:
    description: "The service tenant id of the service which serves the VS Code Tools API"
    required: true
  clientId:
    description: "The service client id of the service which serves the VS Code Tools API"
    required: true
  clientSecret:
    description: "The service client secret of the service which serves the VS Code Tools API"
    required: true
  pull_request:
    description: 'Pull request object - used in webhooks'
    required: false
  repository:
    description: 'Repository object - used in webhooks'
    required: false
  pr_number:
    description: 'Pull request number - used in webhooks'
    required: false
  action:
    description: 'Action being taken - used in webhooks'
    required: false
  repo_name:
    description: 'Repository name - used in webhooks'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
