name: 'Code Review Chat'
description: 'Notify in chat about build results.'
author: 'Jackson Kearl / Logan Ramos'
inputs:
  app_id:
    description: GitHub App ID
    required: true
  app_installation_id:
    description: GitHub App Installation ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true
  slack_token:
    description: Slack token.
    required: true
  slack_user_token:
    description: 'Elevated user token for actions requiring admin'
    required: false
  notification_channel_id:
    description: 'Which channel to send notifications to. Defaults to none.'
    required: true
  slack_bot_name:
    description: 'Required when doing using in queue mode (deletions enabled on close)'
    required: true
  pull_request:
    description: 'Pull request object - used in webhooks'
    required: false
  repository:
    description: 'Repository object - used in webhooks'
    required: false
  pr_number:
    description: 'Pull request number - used in webhooks'
    required: false
  action:
    description: 'Action being taken - used in webhooks'
    required: false
  repo_name:
    description: 'Repository name - used in webhooks'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
